### ISSUE TITLE
Relative load

### ISSUE THREAD

**Issue by spacebat** [exercism/xlisp#126] opened 2016-12-06 22:36 UTC
Because there is no asd file, I find myself going to the test file to load it first. But in my emacs/slime environment, where `*default-pathname-defaults*` is likely my home directory or elsewhere, this form fails:

`#-xlisp-test (load "...")`

I've been changing that load form to: 

`(load (merge-pathnames "..." (or *load-pathname* *default-pathname-defaults*)))`

If this seems reasonable I'm happy to make a PR.

Also, nothing seems to provide the `:xlisp-test` feature - am I missing something?

**Comment by verdammelt** [comment] 2016-12-07 02:09
* `xlisp-test` feature is provided during our builds. In our build we 'manually' load `example.lisp` and then the test file. 
* I think changing the load line to something like `(load (merge-pathnames "file" *load-pathname*))` would be good.

**Comment by spacebat** [comment] 2016-12-07 10:51
PR submitted

**Comment by wobh** [comment] 2016-12-12 05:51
The load error is "by design" for better or worse. It reminds me to use `,cd` in slime to change the default directory, then, of course, loading works. I probably didn't even think to document that. Sorry.

Setting up to load the merged path is a sensible improvement. I would only suggest that, we also move the load expression to line two or three---beneath `ql:quickload`. That at least makes it clearer that this an external requirement and not really part of the test package.

For example:

```lisp
(ql:quickload "lisp-unit")
#-xlisp-test (load (merge-pathnames "raindrops"
                                    (or *load-pathname*
                                        *default-pathname-defaults*)))

(defpackage #:raindrops-test
  (:use #:common-lisp #:lisp-unit))

(in-package #:raindrops-test)

...
```

**Comment by verdammelt** [comment] 2016-12-12 13:48
@wobh Organizing the loading and the package shenanigans is a good idea.

**Closed** 2017-03-04 16:40 UTC
